#
# Time-stamp: <Thursday 14 May 2020 / _config.yml>
#

# Site parameters
title: Gone
subtitle: But Not Forgotten
description: >- # this means to ignore newlines until the next value
  Things that we have no longer but I liked and remember.
author: Ian Stark
email: ian@stark.net
avatar: assets/images/avatar.jpg

# Location for site
url: "https://gone-stark-scot.github.io" 

# Invoke the Prologue theme
remote_theme: chrisbobbe/jekyll-theme-prologue
